### ISSUE TITLE
我这里有个Bug，想问一下您，能把我看看嘛大佬，有点着急！！

### ISSUE THREAD

**Issue by hdz717** [djh-sudo/PGP-for-privacy-email#2]
我在发送邮件的时候可以发送成功，但是收邮件的人无法收到，显示的是下面的问题
java.security.NoSuchProviderException: No such provider: BC
	at javax.crypto.Cipher.getInstance(Cipher.java:592)
	at PGPIDEA.Decrypt(PGPIDEA.java:118)
	at ClientPanel.recvEmail(ClientPanel.java:171)
	at ClientPanel.Request(ClientPanel.java:242)
	at Client$3$1.run(Client.java:277)
![image](https://user-images.githubusercontent.com/58972429/144803039-dcbb014a-8be7-4949-888e-8bb1e6780223.png)
我看你的演示里面没有问题，但是我这里出现了IDEA的解密错误

**Comment by djh-sudo** [comment]
IDEA算法应该不是默认自带的，需要您注册和配置相关的包才能使用！

**Comment by djh-sudo** [comment]
大概有两种解决办法，如果可以替代，你可以使用DES/AES这样比较主流的加密方法，这些包应该是默认就配置好的，如果一定要使用IDEA算法，可以去浏览器搜索“Java IDEA加密"这样的关键字，配置好后，就可以使用。
